name = "MOD_TITLE"
author = "Andx"
prefix = "MOD_PREFIX"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.publish]
description = "workshop/steam_description.md"
changelog = "CHANGELOG.md"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md",
]
